# Generated by Django 6.1 on 2026-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Alex Carter', max_length=100)),
                ('role', models.CharField(default='Senior Frontend Engineer', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, default='San Francisco, CA', max_length=100)),
                ('email', models.EmailField(blank=True, default='alex@portfolio.dev', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (415) 555-2671', max_length=30)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of tags e.g. ['React','Tailwind']")),
                ('gradient', models.CharField(choices=[('from-violet-600 to-indigo-600', 'Violet → Indigo'), ('from-fuchsia-600 to-pink-600', 'Fuchsia → Pink'), ('from-cyan-500 to-blue-600', 'Cyan → Blue'), ('from-emerald-500 to-teal-600', 'Emerald → Teal'), ('from-orange-500 to-red-600', 'Orange → Red')], default='from-violet-600 to-indigo-600', max_length=100)),
                ('demo_url', models.URLField(blank=True, default='#')),
                ('code_url', models.URLField(blank=True, default='#')),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('icon', models.CharField(blank=True, default='◆', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
