# Generated by Django 6.1 on 2026-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_email_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, help_text='Cover photo managed in Django admin — visitors cannot upload', null=True, upload_to='project_covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='emoji',
            field=models.CharField(blank=True, default='💻', help_text='Fallback cover icon shown when no cover image is uploaded', max_length=10),
        ),
    ]
