# Generated by Django 6.1 on 2026-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_cover_project_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, default='', help_text="Short stack line shown under the title e.g. 'Django, PostgreSQL'", max_length=200),
        ),
    ]
