# Generated by Django 6.1 on 2026-09-12 09:30

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV in Django admin — visitors download it from the portfolio hero button', null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), api.models.validate_cv_size]),
        ),
    ]
